import Head from "next/head";
import styles from "../styles/Home.module.scss";
import product from "../Images/product.png";
import firstProb from "../Images/headProb.jpg";
import secondProb from "../Images/mouthProb.jpg";
import thirdProb from "../Images/noiseProb.jpg";
import fouthProb from "../Images/faceProb.jpg";
import proP from "../Images/prod.png";
import ghana from "../Images/ghana.webp";
import camelia from "../Images/c.gif";
import secret from '../Images/secret.png';
import bgBenifet from '../Images/benifet.png';
import { FaCartPlus } from "react-icons/fa";
import { Button } from "@material-ui/core";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>
        {`
          body {
            width: 100%;
            height: 100%;
            margin: 0%;
            padding: 0%;
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
            direction: rtl;
            font-family: "Amiri", serif;
          }
        `}
      </style>
      <section id="gif">
        <div className={styles.__Parent}>
          <div className={styles.__Child__pa}>
            <div>
              <img src={proP} width="100%" height="100%" alt="" />
            </div>
            <div className={styles.__Child_content}>
              <h2>
                البشرة النّـــآصعة
                <br />
                سر جمآل المرأة
              </h2>
              <Button variant="contained" color="secondary">
                أطــلبي الآن
              </Button>
            </div>
          </div>
        </div>
      </section>
      <section id="problems">
        <div className={styles.__parent_Prob}>
          <div className={styles._porB__Child}>
            <div>
              <h1>سبب الشيخوخة هو نقص الريتينول</h1>
              <p>
                بعد 35 عامًا ، تتلاشى بشرتك حتمًا. يتباطأ إنتاج الريتينول ، وهو
                محفز طبيعي لشباب البشرة.
              </p>
            </div>
            <div className={styles.__four__Prob}>
              <div className={styles.__each_Prob}>
                <img src={firstProb} width="100%" height="100%" alt="" />
                <h5> أكياس تحت العين</h5>
              </div>
              <div className={styles.__each_Prob}>
                <img src={secondProb} width="100%" height="100%" alt="" />
                <h5>خطوط التعبير</h5>
              </div>
              <div className={styles.__each_Prob}>
                <img src={thirdProb} width="100%" height="100%" alt="" />
                <h5>الطيات الأنفية</h5>
              </div>
              <div className={styles.__each_Prob}>
                <img src={fouthProb} width="100%" height="100%" alt="" />
                <h5>محيط الوجه "العائم"</h5>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="productTalk">
        <div className={styles.__product}>
          <div className={styles.__product__Child}>
            <div className={styles.__content_Product}>
              <p>
                من خلال اختراق خلايا الجلد
                <br />
                ينشط الباكوتشيول المسارات الكيميائية المسؤولة عن إنتاج الكولاجين
                <br />
                ويقلل من مخاطر التغيرات المبكرة المرتبطة بالعمر.
              </p>
              <Button variant="contained" color="secondary">
                أطــلبي الآن
              </Button>
            </div>
            <div>
              <img src={product} width="100%" height="100%" alt="" />
            </div>
          </div>
        </div>
      </section>
      <section id="secret">
        <div className={styles.__smile}>
          <div className={styles.__smile__Child}>
            <div className={styles.__handle__ttz}>
              <img
                src="https://media.giphy.com/media/3oEjHCUBcm1HUHPPZm/source.gif"
                width="100%"
                height="100%"
                alt=""
              />
            </div>
            <div className={styles.__content__smile}>
              <div>
                <h2>رجعي الإبتســآمة ليك و لكآع اللّي دآيرين بك</h2>
              </div>
              <div>
                <Button variant="contained" color="secondary">
                  أطــلبي الآن{" "}
                  <span>
                    <FaCartPlus />
                  </span>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="ghana">
        <div className={styles.__ghana}>
          <div className={styles.__ghana__Child}>
            <div className={styles.__handl_Ghana}>
              <img src={ghana} width="100%" height="100%" alt="" />
            </div>
            <div className={styles.__content__ghana}>
              <div>
                <h2>
                  هدآ هو الوقت بآش تخلصي من التجآعيد <br />
                  هدآ هو الوقت فين تبآني زوينة <br />
                  وحنآ جبنا لك الحل...
                </h2>
              </div>
              <div>
                <Button variant="contained" color="secondary">
                  أطــلبي الآن{" "}
                  <span>
                    <FaCartPlus />
                  </span>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="secret">
        <div className={styles.__secret}>
          <div className={styles.__secret__Child}>
            <div className={styles.__handle__ttz}>
              <img src={camelia} width="100%" height="100%" alt="" />
            </div>
            <div className={styles.__content__secret}>
              <div>
                <h2>
                  تألــقي من جديد .
                  <br />
                  الإبتسآمة ديالك ، هي الهدف ديآلنا
                </h2>
              </div>
              <div>
                <Button variant="contained" color="secondary">
                  أطــلبي الآن{" "}
                  <span>
                    <FaCartPlus />
                  </span>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="definition">
        <div style={{background:`url(${bgBenifet})`,backgroundSize:'cover',backgroundRepeat:'no-repeat',backgroundAttachment:'fixed'}} className={styles.__dif__Dproduct}>
          <h1>شنآهو السر ديآل TEST ؟</h1>
          <div  className={styles.__child__Dif}>
            <div>
              <p>
                ينشط باكوتشيول إنتاج الكولاجين من النوع الأول والثالث والرابع
                (الريتينول "مسؤول" فقط عن النوع الأول من الكولاجين)
                <br />
                ويثبط عمل الإنزيمات التي تعطل التمثيل الغذائي للبروتين وخلايا الجلد.
                <br />
                إنه لا يعمل فقط على سطح البشرة ، ولكنه يخترق أيضًا أعمق طبقات الأدمة
                ، مما يؤدي إلى تشغيل آلية تجديد الخلايا من الداخل.
              </p>
              <p>
              العنصر النشط في Rechiol هو bakuchiol ، وهو بديل نباتي للريتينول.<br/>
              يتم استخلاص المركز النباتي هذا في الهند من نبات نادر يسمى Cullen corylifolium.
              </p>
            </div>
            <div>
              <img src={secret} width="100%" height="100%" alt=""/>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
